# Generated by Django 6.0.4 on 2026-06-03 10:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_chat_name_chat_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmember',
            old_name='user',
            new_name='member',
        ),
        migrations.AlterUniqueTogether(
            name='chatmember',
            unique_together={('chat', 'member')},
        ),
    ]
