# Generated by Django 6.0.4 on 2026-06-12 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_view',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='feed.post'),
        ),
    ]
