# Generated by Django 6.0.4 on 2026-05-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='is_accepted',
            new_name='subscription_status',
        ),
    ]
