# Generated by Django 6.0.4 on 2026-04-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_id_alter_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='NoName', max_length=30),
        ),
    ]
