# Generated by Django 6.0.4 on 2026-04-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rename_postview_post_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_view',
            name='post',
        ),
    ]
