# Generated by Django 6.0.4 on 2026-04-29 10:55

import randomslugfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_remove_post_view_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=10, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
