# Generated by Django 6.0.4 on 2026-04-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_tag_id_alter_post_slug_alter_tag_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.SlugField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
