# Generated by Django 6.0.4 on 2026-06-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_parent_stickermessage_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='chat_name',
            new_name='name',
        ),
    ]
