# Generated by Django 6.0.4 on 2026-06-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_user_chatmember_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickermessage',
            name='status',
            field=models.IntegerField(choices=[(1, 'sent'), (2, 'delivered'), (3, 'read')], default=1),
        ),
    ]
